### ISSUE TITLE
test almost 16

### ISSUE THREAD

**Issue by andresmgsl** [andresmgsl/white-label-app-test#16]

**Comment by ghost** [comment]
# 💰 Bounty Enabled 2
This issue has an active bounty. [Inspect the transaction](https://explorer.solana.com/tx/2xxHctecdfmPiw1nDuQao94fyiz6qBRriWebwcCVunh3bK8CvTxC3tUuF8TEcS6JUWnLuparD8ANv73U1vT9zRfa?cluster=custom&customUrl=https%3A%2F%2Fapi.devnet.solana.com) in the Solana Explorer.
