### ISSUE TITLE
test almost 17

### ISSUE THREAD

**Issue by andresmgsl** [andresmgsl/white-label-app-test#17]

**Comment by ghost** [comment]
# 💰 Bounty Enabled 2
This issue has an active bounty. [Inspect the transaction](https://explorer.solana.com/tx/TvBdDK5sDjBk4pEemBedPvMHo6CYUP7TiKvTFedxtfGYixaUNmhZWgegsydmweeAgLsmFJPsEk6wcVjsupEnVkd?cluster=custom&customUrl=https%3A%2F%2Fapi.devnet.solana.com) in the Solana Explorer.
