### ISSUE TITLE
testing 18

### ISSUE THREAD

**Issue by andresmgsl** [andresmgsl/white-label-app-test#18]

**Comment by ghost** [comment]
# 💰 Bounty Enabled 2
This issue has an active bounty. [Inspect the transaction](https://explorer.solana.com/tx/21rsVP5Apu7q5dTEtJYAxUmnwRRuKijg9VkWBTnMYLgdafSeyFSDd8CZswKVCpPyE9qTcxwVBU3cF8FBSQ15EyMV?cluster=custom&customUrl=https%3A%2F%2Fapi.devnet.solana.com) in the Solana Explorer.
