### ISSUE TITLE
issue 23

### ISSUE THREAD

**Issue by andresmgsl** [andresmgsl/white-label-app-test#23]

**Comment by ghost** [comment]
# 💰 Bounty Enabled
![solana_pay_qr](http://res.cloudinary.com/pwcaguerrero/image/upload/v1652374146/fcbcoivslwtftaz5z1do.png) 
This issue has an active bounty. [Inspect the transaction](https://explorer.solana.com/tx/V3vMnkwbas8kRnYEDYMEMdFKyAN1ESoeYdm2M9Up88cKzSRfGh1fJspLPg7XAFW3rAi3GDYoGP1SUHxJuoiTRHk?cluster=custom&customUrl=https%3A%2F%2Fapi.devnet.solana.com) in the Solana Explorer.
